# Generated by Django 3.0.5 on 2020-04-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200404_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='http://www.newdesignfile.com/postpic/2015/02/funny-no-image-available-icon_68017.jpg', max_length=200),
        ),
    ]
