# Generated by Django 3.0.5 on 2020-06-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200411_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='foo', max_length=40),
            preserve_default=False,
        ),
    ]
